# Generated by Django 4.0.5 on 2022-08-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_is_supervisor_account_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_examiner',
            field=models.BooleanField(default=False),
        ),
    ]
