# Generated by Django 4.0.5 on 2022-09-02 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100)),
                ('type_desc', models.TextField(max_length=500)),
                ('is_open', models.BooleanField(default=False)),
                ('total_marks', models.IntegerField()),
                ('hifdh_marks', models.IntegerField(blank=True, null=True)),
                ('tajweed_marks', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HalaqaType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100)),
                ('type_desc', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyEnrollment',
            fields=[
                ('enrollment_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_hours', models.PositiveIntegerField()),
                ('hours_left', models.PositiveIntegerField()),
                ('enrollment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_of_type', to='maqari.halaqatype')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_hourly_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Halaqa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('halaqa_number', models.IntegerField(unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=7)),
                ('timings', models.TextField(blank=True, max_length=100)),
                ('halaqa_image_url', models.URLField(default='https://live.staticflickr.com/2139/2435364735_dc51a11e83.jpg')),
                ('halaqa_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halaqaat_of_type', to='maqari.halaqatype')),
                ('students', models.ManyToManyField(blank=True, related_name='students_halaqa', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_halaqaat', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_in_halaqaat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('attendance', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], default='Absent', max_length=10)),
                ('dars', models.CharField(blank=True, default='none', max_length=50)),
                ('dars_pages', models.FloatField(blank=True, default=0)),
                ('taqdeer_dars', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Not Acceptable', 'Not Acceptable'), ('Not Recited', 'Not Recited')], default='Not Recited', max_length=20)),
                ('murajia', models.CharField(blank=True, default='none', max_length=100)),
                ('murajia_pages', models.IntegerField(blank=True, default=0)),
                ('taqdeer_murajia', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Not Acceptable', 'Not Acceptable'), ('Not Recited', 'Not Recited')], default='Not Recited', max_length=20)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_stats', to=settings.AUTH_USER_MODEL)),
                ('halaqa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halaqa_student_stats', to='maqari.halaqa')),
            ],
            options={
                'unique_together': {('account', 'halaqa', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_year', models.IntegerField(blank=True, null=True)),
                ('exam_timing', models.TextField(max_length=100)),
                ('exam_from', models.CharField(max_length=50, null=True)),
                ('exam_till', models.CharField(max_length=50, null=True)),
                ('number_of_juz', models.FloatField(null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('rating', models.CharField(choices=[('Excellent', 'Excellent'), ('Very_Good', 'Very Good'), ('Good', 'Good'), ('Fail', 'Fail'), ('Absent', 'Absent'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('total_marks_obtained', models.FloatField(blank=True, null=True)),
                ('hifdh_marks_obtained', models.FloatField(blank=True, null=True)),
                ('tajweed_marks_obtained', models.FloatField(blank=True, null=True)),
                ('exam_halaqah_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_of_halaqa_type', to='maqari.halaqatype')),
                ('exam_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_of_type', to='maqari.examtype')),
                ('examiner1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Examiner1_exams', to=settings.AUTH_USER_MODEL)),
                ('examiner2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Examiner2_exams', to=settings.AUTH_USER_MODEL)),
                ('halaqa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halaqa_exams', to='maqari.halaqa')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'exam_type', 'exam_halaqah_type')},
            },
        ),
    ]
