# Generated by Django 4.0.5 on 2022-08-01 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('type_desc', models.TextField(max_length=500)),
                ('is_open', models.BooleanField(default=False)),
                ('total_marks', models.IntegerField()),
                ('hifdh_marks', models.IntegerField(blank=True)),
                ('tajweed_marks', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HalaqaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('type_desc', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Halaqa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halaqa_number', models.IntegerField(unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=7)),
                ('timings', models.TextField(blank=True, max_length=100)),
                ('halaqa_image_url', models.URLField(default='https://live.staticflickr.com/2139/2435364735_dc51a11e83.jpg')),
                ('halaqa_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halaqaat_of_type', to='maqari.halaqatype')),
                ('students', models.ManyToManyField(blank=True, related_name='students_halaqa', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_halaqaat', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_in_halaqaat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('exam_year', models.IntegerField(null=True)),
                ('exam_timing', models.TextField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('exam_from', models.CharField(max_length=50, null=True)),
                ('exam_till', models.CharField(max_length=50, null=True)),
                ('number_of_juz', models.FloatField(null=True)),
                ('rating', models.CharField(choices=[('Excellent', 'Excellent'), ('Very_Good', 'Very Good'), ('Good', 'Good'), ('Fail', 'Fail'), ('Absent', 'Absent'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('total_marks_obtained', models.FloatField(blank=True, null=True)),
                ('hifdh_marks_obtained', models.FloatField(blank=True, null=True)),
                ('tajweed_marks_obtained', models.FloatField(blank=True, null=True)),
                ('exam_halaqah_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_of_halaqa_type', to='maqari.halaqatype')),
                ('exam_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_of_type', to='maqari.examtype')),
                ('examiner1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Examiner1_exams', to=settings.AUTH_USER_MODEL)),
                ('examiner2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Examiner2_exams', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_exams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
