# Generated by Django 4.0.5 on 2022-07-30 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HalaqaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('type_desc', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Halaqa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halaqa_number', models.IntegerField(unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=7)),
                ('timings', models.TextField(blank=True, max_length=100)),
                ('halaqa_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halaqaat_of_type', to='maqari.halaqatype')),
                ('students', models.ManyToManyField(related_name='students_halaqa', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_halaqaat', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_in_halaqaat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
