# Generated by Django 4.0.5 on 2022-08-16 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maqari', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], default='Absent', max_length=10)),
                ('dars', models.CharField(max_length=50)),
                ('taqdeer_dars', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Not Acceptable', 'Not Acceptable'), ('Not Recited', 'Not Recited')], default='Not Recited', max_length=20)),
                ('murajia', models.CharField(max_length=100)),
                ('taqdeer_murajia', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Not Acceptable', 'Not Acceptable'), ('Not Recited', 'Not Recited')], default='Not Recited', max_length=20)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_stats', to=settings.AUTH_USER_MODEL)),
                ('halaqa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halaqa_student_stats', to='maqari.halaqa')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.IntegerField()),
                ('hours_left', models.IntegerField()),
                ('enrollment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_of_type', to='maqari.halaqatype')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
