# Generated by Django 4.0.5 on 2022-08-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqari', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyenrollment',
            name='enrollment_number',
            field=models.PositiveIntegerField(default=499906, unique=True),
        ),
    ]
