# Generated by Django 4.0.5 on 2022-08-17 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maqari', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='halaqa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halaqa_exams', to='maqari.halaqa'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('student', 'exam_type', 'exam_halaqah_type')},
        ),
        migrations.CreateModel(
            name='HourlyEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.PositiveIntegerField(default=21134, unique=True)),
                ('total_hours', models.PositiveIntegerField()),
                ('hours_left', models.PositiveIntegerField()),
                ('enrollment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_of_type', to='maqari.halaqatype')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_hourly_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], default='Absent', max_length=10)),
                ('dars', models.CharField(blank=True, default='none', max_length=50)),
                ('dars_pages', models.FloatField(blank=True, default=0)),
                ('taqdeer_dars', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Not Acceptable', 'Not Acceptable'), ('Not Recited', 'Not Recited')], default='Not Recited', max_length=20)),
                ('murajia', models.CharField(blank=True, default='none', max_length=100)),
                ('murajia_pages', models.IntegerField(blank=True, default=0)),
                ('taqdeer_murajia', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Not Acceptable', 'Not Acceptable'), ('Not Recited', 'Not Recited')], default='Not Recited', max_length=20)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_stats', to=settings.AUTH_USER_MODEL)),
                ('halaqa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halaqa_student_stats', to='maqari.halaqa')),
            ],
            options={
                'unique_together': {('account', 'halaqa', 'date')},
            },
        ),
    ]
