# Generated by Django 4.0.5 on 2022-07-30 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maqari', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halaqa',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students_halaqa', to=settings.AUTH_USER_MODEL),
        ),
    ]
