# Generated by Django 4.0.5 on 2022-08-16 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maqari', '0002_stats_hourlyenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyenrollment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_hourly_enrollments', to=settings.AUTH_USER_MODEL),
        ),
    ]
