# Generated by Django 4.0.5 on 2022-08-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqari', '0003_alter_hourlyenrollment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourlyenrollment',
            name='enrollment_number',
            field=models.IntegerField(default=2316, unique=True),
        ),
    ]
