# Generated by Django 4.0.5 on 2022-08-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqari', '0004_hourlyenrollment_enrollment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='dars_pages',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='murajia_pages',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hourlyenrollment',
            name='enrollment_number',
            field=models.IntegerField(default=6845, unique=True),
        ),
    ]
