# Generated by Django 4.0.5 on 2022-08-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqari', '0005_stats_dars_pages_stats_murajia_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyenrollment',
            name='enrollment_number',
            field=models.IntegerField(default=103571, unique=True),
        ),
    ]
