# Generated by Django 4.0.5 on 2022-08-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqari', '0006_alter_hourlyenrollment_enrollment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyenrollment',
            name='enrollment_number',
            field=models.PositiveIntegerField(default=708347, unique=True),
        ),
    ]
