# Generated by Django 4.0.5 on 2022-08-17 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maqari', '0009_alter_hourlyenrollment_enrollment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyenrollment',
            name='enrollment_number',
            field=models.PositiveIntegerField(default=377597, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='stats',
            unique_together={('account', 'halaqa', 'date')},
        ),
    ]
