# Generated by Django 4.0.5 on 2022-08-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqari', '0011_alter_hourlyenrollment_enrollment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyenrollment',
            name='enrollment_number',
            field=models.PositiveIntegerField(default=431035, unique=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='dars',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='stats',
            name='dars_pages',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='murajia',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='stats',
            name='murajia_pages',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
