# Generated by Django 4.0.5 on 2022-08-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqari', '0012_alter_hourlyenrollment_enrollment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyenrollment',
            name='enrollment_number',
            field=models.PositiveIntegerField(default=498406, unique=True),
        ),
    ]
