# Generated by Django 4.0.5 on 2022-08-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqari', '0014_exam_halaqa_alter_hourlyenrollment_enrollment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hourlyenrollment',
            name='enrollment_number',
            field=models.PositiveIntegerField(default=524154, unique=True),
        ),
    ]
