# Generated by Django 4.0.5 on 2022-08-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqari', '0015_alter_exam_exam_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hourlyenrollment',
            name='enrollment_number',
            field=models.PositiveIntegerField(default=93804, unique=True),
        ),
    ]
