# Generated by Django 4.0.5 on 2022-08-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqari', '0016_alter_exam_exam_date_alter_exam_exam_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyenrollment',
            name='enrollment_number',
            field=models.PositiveIntegerField(default=890881, unique=True),
        ),
    ]
